### ISSUE TITLE
Does not display array brackets in one-liner windows

### ISSUE THREAD

**Issue by kleinepls** [Fildo7525/pretty_hover#26] opened 2024-10-07 15:07 UTC
After the changes introduced in https://github.com/Fildo7525/pretty_hover/issues/24, the library does not display array brackets in one-liner hover windows. Example with Golang `map` types:
![image](https://github.com/user-attachments/assets/801c3b5e-4d3c-48e7-aa1e-12974fa94b46)

However the rendering is correct when focusing the window:
![image](https://github.com/user-attachments/assets/25a1e1c2-f2fe-45f8-af47-1c8caaf996e4)

Is it possible to replicate the focused window behavior?

**Comment by Fildo7525** [comment] 2024-10-28 11:01
This is caused by markdown rendering. You can see the markdown characters only if you focus on the line where they are located. This also happens in the default hover window

**Comment by Fildo7525** [comment] 2024-10-28 11:02
But I can add a flag, where you will be able to change the behaviour of #24. Is that ok?

**Comment by kleinepls** [comment] 2024-11-05 13:12
This fixes the one-liner, but for hovers with more than one line, it makes the markdown characters visible without focusing the window

![image](https://github.com/user-attachments/assets/fa5c7c4e-070e-4d6d-bd9b-b8a55630a48f)


If it helps testing, you could try creating a `.go` file and typing this:
```
package main

import "net/http"

func main() {
	var x map[int]string
	http.NewServeMux
}
```

then you can hover on `x` and `NewServeMux`

**Comment by Fildo7525** [comment] 2024-11-10 09:24
This is caused by the markdown formatting. If you put anything into brackets it will automatically be highlighted like that. The solution would be to put the backslash in front of the first one, as in the screenshot you sent.

**Comment by Fildo7525** [comment] 2024-11-10 09:38
Ok I have fixed it and ported to the newest master. WIth the code that you have sent it works. If you find anything your let me know. Otherwise can it be merged?

**Closed** 2024-11-11 13:08 UTC
